Fire: node fire.js
OBxCOdes: node codes.js
nodeone: node bot.js
nodetwo: node bot2.js
nodethree: node Mod.js
nodefour: node BC.js
nodefive: node tk.js
nodesix: node wl.js
nodeseven: node ga.js
nodeeight: node me.js
nodeeleven: node Zzetchen.js
cofeone: node cofesexy.js
cofetwo: node cofesexy2.js
cofethree: node cofesexy3.js
Helper: node Helper.js
FMone: node sell.js
FMtwo: node FM2.js
FMthree: node FM3.js
music1: node music1.js
music2: node music2.js
music3: node music3.js
fuck: node zaid.js
